name: WakaTime Readme

on:
 schedule:
  - cron: "0 * * * *" # Runs every hour
 workflow_dispatch:

jobs:
 update-readme:
  name: Update WakaTime stats
  runs-on: ubuntu-latest
  steps:
   - uses: athul/waka-readme-stats@v4
     with:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      SHOW_TITLE: true
      SHOW_TIME: true
      SHOW_TOTAL: true
      SHOW_MASKED_TIME: false
